import {
  BarChart,
  Bell,
  Book,
  Briefcase,
  Building,
  Calendar,
  Camera,
  Check,
  Clipboard,
  Clock,
  Cloud,
  Coffee,
  CreditCard,
  DollarSign,
  Download,
  Edit,
  Eye,
  FileText,
  Folder,
  Gift,
  Globe,
  Heart,
  Home,
  Key,
  Layers,
  Lock,
  Mail,
  MapPin,
  Minus,
  Moon,
  Music,
  Phone,
  PieChart,
  Plus,
  Search,
  Settings,
  Shield,
  ShoppingCart,
  Star,
  Sun,
  Tag,
  Trash,
  Truck,
  Unlock,
  Upload,
  User,
  Wifi,
  X,
  Zap
} from "lucide-react"

export const availableIcons = [
  { value: "home", label: "Casa", icon: Home },
  { value: "user", label: "Usuário", icon: User },
  { value: "settings", label: "Configurações", icon: Settings },
  { value: "book", label: "Livro", icon: Book },
  { value: "file-text", label: "Documento", icon: FileText },
  { value: "calendar", label: "Calendário", icon: Calendar },
  { value: "mail", label: "Email", icon: Mail },
  { value: "phone", label: "Telefone", icon: Phone },
  { value: "map-pin", label: "Localização", icon: MapPin },
  { value: "star", label: "Estrela", icon: Star },
  { value: "heart", label: "Coração", icon: Heart },
  { value: "shield", label: "Escudo", icon: Shield },
  { value: "briefcase", label: "Maleta", icon: Briefcase },
  { value: "camera", label: "Câmera", icon: Camera },
  { value: "music", label: "Música", icon: Music },
  { value: "bell", label: "Notificação", icon: Bell },
  { value: "check", label: "Confirmar", icon: Check },
  { value: "x", label: "Fechar", icon: X },
  { value: "edit", label: "Editar", icon: Edit },
  { value: "trash", label: "Lixeira", icon: Trash },
  { value: "plus", label: "Adicionar", icon: Plus },
  { value: "minus", label: "Remover", icon: Minus },
  { value: "search", label: "Pesquisar", icon: Search },
  { value: "eye", label: "Visualizar", icon: Eye },
  { value: "lock", label: "Bloquear", icon: Lock },
  { value: "unlock", label: "Desbloquear", icon: Unlock },
  { value: "shopping-cart", label: "Carrinho", icon: ShoppingCart },
  { value: "tag", label: "Etiqueta", icon: Tag },
  { value: "gift", label: "Presente", icon: Gift },
  { value: "globe", label: "Mundo", icon: Globe },
  { value: "download", label: "Baixar", icon: Download },
  { value: "upload", label: "Enviar", icon: Upload },
  { value: "cloud", label: "Nuvem", icon: Cloud },
  { value: "wifi", label: "Wi-Fi", icon: Wifi },
  { value: "credit-card", label: "Cartão", icon: CreditCard },
  { value: "dollar-sign", label: "Dinheiro", icon: DollarSign },
  { value: "chart-bar", label: "Relatório", icon: BarChart },
  { value: "pie-chart", label: "Gráfico", icon: PieChart },
  { value: "clock", label: "Relógio", icon: Clock },
  { value: "sun", label: "Sol", icon: Sun },
  { value: "moon", label: "Lua", icon: Moon },
  { value: "coffee", label: "Café", icon: Coffee },
  { value: "truck", label: "Entrega", icon: Truck },
  { value: "building", label: "Prédio", icon: Building },
  { value: "layers", label: "Camadas", icon: Layers },
  { value: "folder", label: "Pasta", icon: Folder },
  { value: "clipboard", label: "Anotações", icon: Clipboard },
  { value: "key", label: "Chave", icon: Key },
  { value: "zap", label: "Energia", icon: Zap }
]
